[package]
name = "kuwahara"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
clap = {version = "4.0", features = ["derive"]}
indicatif = "0.17.8"
vecmath = "1.0.0"
ndarray = "0.16.1"
ndarray-conv = "0.4.1"
show-image = "0.14.0"
